### ISSUE TITLE
pretrained model 

### ISSUE THREAD

**Issue by Redamancy0222** [pp00704831/BANet#8]
Hello, first of all, thank you for your outstanding work. The pretrained model link you have on Google Drive seems to be invalid, displaying 404. Can you please provide the pre trained model again.

**Comment by pp00704831** [comment]
Hello,

Thank you for your interest. I can connect to the link. I am not sure why you can not connect to the link.
Could you please try this link again?
https://drive.google.com/drive/u/2/folders/0B1M5aNe46QPlflAtXzR2RzhwQWkzbGoyaS1HYlVSY2FBd1NMZ1BHbFFEdnROQl9NQjZDNVE?resourcekey=0-MBS_f0fXHrFCK2EiMswB6Q
